In [1]:
# set up for pandas, numpy, matplotlib, read csv file
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

## Dataset 1: 2021 CDC Data - ART Services and Profiles

In [2]:
# read csv file
df = pd.read_csv('./Input/2021_ART__Services_and_Profiles_20240530.csv')
df.head()

,Year,LocationAbbr,LocationDesc,FacilityName,MedicalDirector,Address,City,Zipcode,Phone,Clinic Status,Topic,SubTopic,Data_Value,ClinicId,TopicId,SubTopicId,Geolocation
0,2021,IL,Illinois,Institute for Human Reproduction (IHR),"David P. Cohen, MD","409 W. Huron St, Suite 500",Chicago,60654.0,(312) 288-6420,Open,Clinic Services & Profile,Total cycles,1192,1,TOP01,ST01,POINT (-87.639 41.8945)
1,2021,IL,Illinois,Institute for Human Reproduction (IHR),"David P. Cohen, MD","409 W. Huron St, Suite 500",Chicago,60654.0,(312) 288-6420,Open,Clinic Services & Profile,Fertility preservation cycles,99,1,TOP01,ST02,POINT (-87.639 41.8945)
2,2021,IL,Illinois,Institute for Human Reproduction (IHR),"David P. Cohen, MD","409 W. Huron St, Suite 500",Chicago,60654.0,(312) 288-6420,Open,Clinic Services & Profile,Pregnancies,236,1,TOP01,ST03,POINT (-87.639 41.8945)
3,2021,IL,Illinois,Institute for Human Reproduction (IHR),"David P. Cohen, MD","409 W. Huron St, Suite 500",Chicago,60654.0,(312) 288-6420,Open,Clinic Services & Profile,Deliveries,193,1,TOP01,ST04,POINT (-87.639 41.8945)
4,2021,IL,Illinois,Institute for Human Reproduction (IHR),"David P. Cohen, MD","409 W. Huron St, Suite 500",Chicago,60654.0,(312) 288-6420,Open,Clinic Services & Profile,Total infants born,195,1,TOP01,ST05,POINT (-87.639 41.8945)

In [3]:
# filter to only rows where "SubTopic" = either "Donor egg services" or "Donated embryo services"
df = df[(df['SubTopic'] == 'Donor egg services') | (df['SubTopic'] == 'Donated embryo services')]
df.head(20)

,Year,LocationAbbr,LocationDesc,FacilityName,MedicalDirector,Address,City,Zipcode,Phone,Clinic Status,Topic,SubTopic,Data_Value,ClinicId,TopicId,SubTopicId,Geolocation
5,2021,IL,Illinois,Institute for Human Reproduction (IHR),"David P. Cohen, MD","409 W. Huron St, Suite 500",Chicago,60654.0,(312) 288-6420,Open,Clinic Services & Profile,Donor egg services,Yes,1,TOP01,ST09,POINT (-87.639 41.8945)
6,2021,IL,Illinois,Institute for Human Reproduction (IHR),"David P. Cohen, MD","409 W. Huron St, Suite 500",Chicago,60654.0,(312) 288-6420,Open,Clinic Services & Profile,Donated embryo services,Yes,1,TOP01,ST10,POINT (-87.639 41.8945)
17,2021,PA,Pennsylvania,Shady Grove Fertility-Pennsylvania,"Isaac E. Sasson, MD, PHD",945 Chesterbrook Blvd,Wayne,19087.0,(610) 981-6000,Open,Clinic Services & Profile,Donor egg services,Yes,2,TOP01,ST09,POINT (-75.4619 40.0681)
18,2021,PA,Pennsylvania,Shady Grove Fertility-Pennsylvania,"Isaac E. Sasson, MD, PHD",945 Chesterbrook Blvd,Wayne,19087.0,(610) 981-6000,Open,Clinic Services & Profile,Donated embryo services,Yes,2,TOP01,ST10,POINT (-75.4619 40.0681)
29,2021,TX,Texas,"Houston Infertility Clinic, Sonja Kristiansen, MD","Sonja B. Kristiansen, MD","9055 Katy Freeway, Suite 450",Houston,77024.0,(713) 862-6181,Open,Clinic Services & Profile,Donor egg services,No,3,TOP01,ST09,POINT (-95.5123 29.7836)
30,2021,TX,Texas,"Houston Infertility Clinic, Sonja Kristiansen, MD","Sonja B. Kristiansen, MD","9055 Katy Freeway, Suite 450",Houston,77024.0,(713) 862-6181,Open,Clinic Services & Profile,Donated embryo services,No,3,TOP01,ST10,POINT (-95.5123 29.7836)
41,2021,FL,Florida,"Advanced Reproductive Specialists, Jacksonvill...","Michael D. Fox, MD","7051 Southpoint Pkwy, Suite 200",Jacksonville,32216.0,(904) 493-2229,Open,Clinic Services & Profile,Donor egg services,Yes,4,TOP01,ST09,POINT (-81.5907 30.2577)
42,2021,FL,Florida,"Advanced Reproductive Specialists, Jacksonvill...","Michael D. Fox, MD","7051 Southpoint Pkwy, Suite 200",Jacksonville,32216.0,(904) 493-2229,Open,Clinic Services & Profile,Donated embryo services,No,4,TOP01,ST10,POINT (-81.5907 30.2577)
53,2021,PA,Pennsylvania,Penn State Milton S. Hershey Medical Center,"Samantha Butts, MD","35 Hope Dr, Suite 202",Hershey,17033.0,(717) 531-6731,Open,Clinic Services & Profile,Donor egg services,No,6,TOP01,ST09,POINT (-76.6611 40.2702)
54,2021,PA,Pennsylvania,Penn State Milton S. Hershey Medical Center,"Samantha Butts, MD","35 Hope Dr, Suite 202",Hershey,17033.0,(717) 531-6731,Open,Clinic Services & Profile,Donated embryo services,No,6,TOP01,ST10,POINT (-76.6611 40.2702)
65,2021,CA,California,Life IVF Center,"Frank D. Yelian, MD, PHD","3500 Barranca Pkwy, Suite 300",Irvine,92606.0,(949) 788-1133,Open,Clinic Services & Profile,Donor egg services,Yes,7,TOP01,ST09,POINT (-117.815 33.6863)
66,2021,CA,California,Life IVF Center,"Frank D. Yelian, MD, PHD","3500 Barranca Pkwy, Suite 300",Irvine,92606.0,(949) 788-1133,Open,Clinic Services & Profile,Donated embryo services,Yes,7,TOP01,ST10,POINT (-117.815 33.6863)
77,2021,PA,Pennsylvania,Society Hill Reproductive Medicine,"Maureen P. Kelly, MD","822 Pine St, Suite 4B",Philadelphia,19107.0,(215) 829-8110,Open,Clinic Services & Profile,Donor egg services,Yes,8,TOP01,ST09,POINT (-75.1561 39.9443)
78,2021,PA,Pennsylvania,Society Hill Reproductive Medicine,"Maureen P. Kelly, MD","822 Pine St, Suite 4B",Philadelphia,19107.0,(215) 829-8110,Open,Clinic Services & Profile,Donated embryo services,Yes,8,TOP01,ST10,POINT (-75.1561 39.9443)
89,2021,OK,Oklahoma,OU Health Reproductive Medicine,"LaTasha B. Craig, MD","840 Research Pkwy, Suite 200",Oklahoma City,73104.0,(405) 271-1616,Open,Clinic Services & Profile,Donor egg services,Yes,9,TOP01,ST09,POINT (-97.5009 35.4775)
90,2021,OK,Oklahoma,OU Health Reproductive Medicine,"LaTasha B. Craig, MD","840 Research Pkwy, Suite 200",Oklahoma City,73104.0,(405) 271-1616,Open,Clinic Services & Profile,Donated embryo services,Yes,9,TOP01,ST10,POINT (-97.5009 35.4775)
101,2021,SC,South Carolina,"Piedmont Reproductive Endocrinology Group, PA","John E. Nichols, MD","17 Caledon Ct, Suite C",Greenville,29615.0,(864) 232-7734,Open,Clinic Services & Profile,Donor egg services,Yes,10,TOP01,ST09,POINT (-82.3396 34.8631)
102,2021,SC,South Carolina,"Piedmont Reproductive Endocrinology Group, PA","John E. Nichols, MD","17 Caledon Ct, Suite C",Greenville,29615.0,(864) 232-7734,Open,Clinic Services & Profile,Donated embryo services,Yes,10,TOP01,ST10,POINT (-82.3396 34.8631)
113,2021,CA,California,Santa Barbara Fertility Center,"René B. Allen, MD","536 E. Arrellaga St, Suite 201",Santa Barbara,93103.0,(805) 965-3400,Open,Clinic Services & Profile,Donor egg services,Yes,12,TOP01,ST09,POINT (-119.703 34.4331)
114,2021,CA,California,Santa Barbara Fertility Center,"René B. Allen, MD","536 E. Arrellaga St, Suite 201",Santa Barbara,93103.0,(805) 965-3400,Open,Clinic Services & Profile,Donated embryo services,Yes,12,TOP01,ST10,POINT (-119.703 34.4331)

In [4]:
# Filter the DataFrame for the year 2021 and the specified SubTopics with Data_Value = 'YES'
df = df[(df['Data_Value'] == 'Yes')]
df.head()

,Year,LocationAbbr,LocationDesc,FacilityName,MedicalDirector,Address,City,Zipcode,Phone,Clinic Status,Topic,SubTopic,Data_Value,ClinicId,TopicId,SubTopicId,Geolocation
5,2021,IL,Illinois,Institute for Human Reproduction (IHR),"David P. Cohen, MD","409 W. Huron St, Suite 500",Chicago,60654.0,(312) 288-6420,Open,Clinic Services & Profile,Donor egg services,Yes,1,TOP01,ST09,POINT (-87.639 41.8945)
6,2021,IL,Illinois,Institute for Human Reproduction (IHR),"David P. Cohen, MD","409 W. Huron St, Suite 500",Chicago,60654.0,(312) 288-6420,Open,Clinic Services & Profile,Donated embryo services,Yes,1,TOP01,ST10,POINT (-87.639 41.8945)
17,2021,PA,Pennsylvania,Shady Grove Fertility-Pennsylvania,"Isaac E. Sasson, MD, PHD",945 Chesterbrook Blvd,Wayne,19087.0,(610) 981-6000,Open,Clinic Services & Profile,Donor egg services,Yes,2,TOP01,ST09,POINT (-75.4619 40.0681)
18,2021,PA,Pennsylvania,Shady Grove Fertility-Pennsylvania,"Isaac E. Sasson, MD, PHD",945 Chesterbrook Blvd,Wayne,19087.0,(610) 981-6000,Open,Clinic Services & Profile,Donated embryo services,Yes,2,TOP01,ST10,POINT (-75.4619 40.0681)
41,2021,FL,Florida,"Advanced Reproductive Specialists, Jacksonvill...","Michael D. Fox, MD","7051 Southpoint Pkwy, Suite 200",Jacksonville,32216.0,(904) 493-2229,Open,Clinic Services & Profile,Donor egg services,Yes,4,TOP01,ST09,POINT (-81.5907 30.2577)

In [5]:
# Count the unique facilities for each SubTopic
unique_facilities_donor_egg = df[df['SubTopic'] == 'Donor egg services']['FacilityName'].nunique()
unique_facilities_donated_embryo = df[df['SubTopic'] == 'Donated embryo services']['FacilityName'].nunique()

In [6]:
print(f"Unique facilities with Donor egg services: {unique_facilities_donor_egg}")
print(f"Unique facilities with Donated embryo services: {unique_facilities_donated_embryo}")

Unique facilities with Donor egg services: 397
Unique facilities with Donated embryo services: 275

In [7]:
# count unique facilities for both SubTopic combined: count the facilities if it provides either "Donor egg services" or "Donated embryo services" 
unique_facilities_combined = df['FacilityName'].nunique()

In [8]:
print(f"Unique facilities with either Donor egg services or Donated embryo services: {unique_facilities_combined}")

Unique facilities with either Donor egg services or Donated embryo services: 407

## Dataset 2: 2021 CDC Data - Patient and Cycle Characteristics

In [3]:
# read csv file: 2021_ART__Patient_and_Cycle_Characteristics_20240530.csv in the "Input" folder
df2 = pd.read_csv('./Input/2021_ART__Patient_and_Cycle_Characteristics_20240530.csv')
df2.head()

,Year,LocationAbbr,LocationDesc,FacilityName,MedicalDirector,Address,City,ZipCode,Phone,Clinic Status,...,Data_Value_num,Data_Value_Footnote_Symbol,Data_Value_Footnote,Cycle_Count,ClinicId,TopicId,QuestionId,BreakOutCategoryId,BreakOutId,Geolocation
0,2021,FL,Florida,"Fertility & IVF Center of Miami, Inc., Fertili...","Fernando Akerman, MD","8950 N. Kendall Dr, Suite 103",Miami,33176.0,(305) 596-4013,Reorganized,...,24.2,NaN,NaN,810.0,241,TOP02,Q001,CAT2,B001,POINT (-80.3407 25.683)
1,2021,FL,Florida,"Fertility & IVF Center of Miami, Inc., Fertili...","Fernando Akerman, MD","8950 N. Kendall Dr, Suite 103",Miami,33176.0,(305) 596-4013,Reorganized,...,25.3,NaN,NaN,810.0,241,TOP02,Q001,CAT2,B002,POINT (-80.3407 25.683)
2,2021,FL,Florida,"Fertility & IVF Center of Miami, Inc., Fertili...","Fernando Akerman, MD","8950 N. Kendall Dr, Suite 103",Miami,33176.0,(305) 596-4013,Reorganized,...,23.1,NaN,NaN,810.0,241,TOP02,Q001,CAT2,B003,POINT (-80.3407 25.683)
3,2021,FL,Florida,"Fertility & IVF Center of Miami, Inc., Fertili...","Fernando Akerman, MD","8950 N. Kendall Dr, Suite 103",Miami,33176.0,(305) 596-4013,Reorganized,...,27.4,NaN,NaN,810.0,241,TOP02,Q001,CAT2,B004,POINT (-80.3407 25.683)
4,2021,FL,Florida,"Fertility & IVF Center of Miami, Inc., Fertili...","Fernando Akerman, MD","8950 N. Kendall Dr, Suite 103",Miami,33176.0,(305) 596-4013,Reorganized,...,1.4,NaN,NaN,810.0,241,TOP02,Q002,CAT14,B009,POINT (-80.3407 25.683)

In [10]:
df2 = df2[df2['Question'] == "What was the percentage of cycles in which patients used donor eggs or embryos?"]
df2

,Year,LocationAbbr,LocationDesc,FacilityName,MedicalDirector,Address,City,ZipCode,Phone,Clinic Status,...,Data_Value_num,Data_Value_Footnote_Symbol,Data_Value_Footnote,Cycle_Count,ClinicId,TopicId,QuestionId,BreakOutCategoryId,BreakOutId,Geolocation
20,2021,FL,Florida,"Fertility & IVF Center of Miami, Inc., Fertili...","Fernando Akerman, MD","8950 N. Kendall Dr, Suite 103",Miami,33176.0,(305) 596-4013,Reorganized,...,2.0,NaN,NaN,810.0,241,TOP02,Q004,CAT2,B001,POINT (-80.3407 25.683)
21,2021,FL,Florida,"Fertility & IVF Center of Miami, Inc., Fertili...","Fernando Akerman, MD","8950 N. Kendall Dr, Suite 103",Miami,33176.0,(305) 596-4013,Reorganized,...,0.5,NaN,NaN,810.0,241,TOP02,Q004,CAT2,B002,POINT (-80.3407 25.683)
22,2021,FL,Florida,"Fertility & IVF Center of Miami, Inc., Fertili...","Fernando Akerman, MD","8950 N. Kendall Dr, Suite 103",Miami,33176.0,(305) 596-4013,Reorganized,...,2.7,NaN,NaN,810.0,241,TOP02,Q004,CAT2,B003,POINT (-80.3407 25.683)
23,2021,FL,Florida,"Fertility & IVF Center of Miami, Inc., Fertili...","Fernando Akerman, MD","8950 N. Kendall Dr, Suite 103",Miami,33176.0,(305) 596-4013,Reorganized,...,27.9,NaN,NaN,810.0,241,TOP02,Q004,CAT2,B004,POINT (-80.3407 25.683)
84,2021,IL,Illinois,Vios Fertility Institute-Crest Hill,"Angie Beltsos, MD",2246 Weber Rd,Crest Hill,60403.0,(815) 725-4161,Reorganized,...,4.6,NaN,NaN,198.0,261,TOP02,Q004,CAT2,B001,POINT (-88.1206 41.5628)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29035,2021,NaN,National,National,NaN,NaN,NaN,NaN,NaN,Open,...,3.0,NaN,NaN,413776.0,9999,TOP02,Q004,CAT2,B002,NaN
29036,2021,NaN,Other,National,NaN,NaN,NaN,NaN,NaN,Open,...,5.1,NaN,NaN,413776.0,9999,TOP02,Q004,CAT2,B003,NaN
29037,2021,NaN,National,National,NaN,NaN,NaN,NaN,NaN,Open,...,5.1,NaN,NaN,413776.0,9999,TOP02,Q004,CAT2,B003,NaN
29038,2021,NaN,Other,National,NaN,NaN,NaN,NaN,NaN,Open,...,21.8,NaN,NaN,413776.0,9999,TOP02,Q004,CAT2,B004,NaN
29039,2021,NaN,National,National,NaN,NaN,NaN,NaN,NaN,Open,...,21.8,NaN,NaN,413776.0,9999,TOP02,Q004,CAT2,B004,NaN

In [11]:
# remove rows where "Facility Name" is "National" 
df2 = df2[df2['FacilityName'] != 'National']

In [12]:
# Create a pivot table
pivot_table = df2.pivot_table(index=['ZipCode', 'ClinicId'], 
                              values=['Cycle_Count', 'Data_Value_num'], 
                              aggfunc={'Cycle_Count': 'median', 'Data_Value_num': 'sum'})

In [13]:
#round the numbers to integer
pivot_table['Cycle_Count'] = pivot_table['Cycle_Count'].round(0).astype(int)
# display the pivot table
pivot_table.head()

                  Cycle_Count  Data_Value_num
ZipCode ClinicId
726.0   274                75             5.0
909.0   145               170             5.6
961.0   338               350            31.4
1199.0  154               761            19.7
1605.0  856                84             0.0

In [14]:
# check the data type of the ZipCode
pivot_table.index.get_level_values(0).dtype

dtype('float64')

In [15]:
# turn the ZipCode into string
pivot_table.index = pivot_table.index.set_levels(pivot_table.index.levels[0].astype(str), level=0)

In [16]:
# remove the ".0" in the ZipCode
pivot_table.index = pivot_table.index.set_levels(pivot_table.index.levels[0].str[:-2], level=0)
pivot_table

                  Cycle_Count  Data_Value_num
ZipCode ClinicId
726     274                75             5.0
909     145               170             5.6
961     338               350            31.4
1199    154               761            19.7
1605    856                84             0.0
...                       ...             ...
98431   718               107             0.0
98502   415               113            15.2
99201   371               336            55.3
99216   513               360            47.8
99603   842                41             0.0

[453 rows x 2 columns]

In [17]:
# Calculate cycles of donor eggs/embryos by clinic
pivot_table['Cycles_of_Donor_Eggs_Embryos'] = (pivot_table['Cycle_Count'] * pivot_table['Data_Value_num']) / 100

In [18]:
# Sum up the total cycles of donor eggs/embryos by clinic
total_cycles = pivot_table['Cycles_of_Donor_Eggs_Embryos'].sum()

In [19]:
total_cycles = round(total_cycles)
print(f"Total cycles of donor eggs/embryos by clinic: {total_cycles}")

Total cycles of donor eggs/embryos by clinic: 137943

In [20]:
national_cycles = pivot_table['Cycle_Count'].sum()
print(f"Total cycles in the nation: {national_cycles}")

Total cycles in the nation: 413761

In [21]:
pecentage_of_donor_cycles = (total_cycles / national_cycles) * 100
print(f"Percentage of cycles in which patients used donor eggs or embryos in 2021: {pecentage_of_donor_cycles:.2f}%")

Percentage of cycles in which patients used donor eggs or embryos in 2021: 33.34%

In [22]:
# Prepare to read Excel file .xls
!pip install xlrd

Requirement already satisfied: xlrd in /Users/charlenelin/.pyenv/versions/3.11.6/lib/python3.11/site-packages (2.0.1)

[notice] A new release of pip is available: 24.1 -> 24.1.2
[notice] To update, run: pip install --upgrade pip

# Dataset 3: 2010 CDC Data

In [4]:
# read excel
df3 = pd.read_excel('./Input/clinic_tables_data_2010.xls', sheet_name='Clinic Table Data Records')
# Display the first few rows of the DataFrame
df3

,OrderID,PrevClinName1,PrevClinName2,ClinCityCode,ClinStateCode,IVF_Rate,GIFT_Rate,ZIFT_Rate,Combo_Rate,ICSI_Rate,...,ThwDnrEmbryosRate,CurrClinNameAll,DonorEgg,DonorEmbryo,SingleWomen,Surrogates,Cryopreservation,SART_Member,Accreditation,state_code
0,1,ALABAMA FERTILITY SPECIALISTS,NaN,BIRMINGHAM,ALABAMA,100%,0%,0%,0%,38%,...,1.5,Alabama Fertility Specialists,Yes,Yes,Yes,No,Yes,Yes,Yes,AL
1,2,ART FERTILITY PROGRAM OF ALABAMA,NaN,BIRMINGHAM,ALABAMA,100%,0%,0%,0%,88%,...,2.0,ART Fertility Program of Alabama,Yes,Yes,Yes,Yes,Yes,Yes,Yes,AL
2,3,UNIVERSITY OF ALABAMA AT BIRMINGHAM,NaN,BIRMINGHAM,ALABAMA,100%,0%,0%,0%,58%,...,2.0,University of Alabama at Birmingham,Yes,No,Yes,Yes,Yes,Yes,Yes,AL
3,4,"HUNTSVILLE REPRODUCTIVE MEDICINE, PC",NaN,HUNTSVILLE,ALABAMA,100%,0%,0%,0%,76%,...,2.1,"Huntsville Reproductive Medicine, PC",Yes,Yes,Yes,Yes,Yes,No,No,AL
4,5,CENTER FOR REPRODUCTIVE MEDICINE,NaN,MOBILE,ALABAMA,100%,0%,0%,0%,84%,...,NaN,Center for Reproductive Medicine,Yes,Yes,No,Yes,Yes,Yes,Yes,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,439,WISCONSIN FERTILITY INSTITUTE,NaN,MIDDLETON,WISCONSIN,100%,0%,0%,0%,94%,...,2.2,Wisconsin Fertility Institute,Yes,Yes,Yes,Yes,Yes,Yes,Yes,WI
439,440,REPRODUCTIVE MEDICINE CENTER,FROEDTERT-MEDICAL COLLEGE,MILWAUKEE,WISCONSIN,100%,0%,0%,0%,92%,...,1.8,"Reproductive Medicine Center, Froedtert-Medica...",Yes,Yes,Yes,Yes,Yes,Yes,Yes,WI
440,441,REPRODUCTIVE SPECIALTY CENTER,NaN,MILWAUKEE,WISCONSIN,100%,0%,0%,0%,46%,...,NaN,Reproductive Specialty Center,Yes,No,Yes,Yes,Yes,Yes,Yes,WI
441,442,"WOMEN'S HEALTH CARE, SC",NaN,WAUKESHA,WISCONSIN,100%,0%,0%,0%,56%,...,NaN,This clinic has closed or reorganized since 20...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WI
442,443,"AURORA HEALTH CARE-AURORA FERTILITY SERVICES, ...",NaN,WEST ALLIS,WISCONSIN,100%,0%,0%,0%,92%,...,2.0,"Aurora Health Care-Aurora Fertility Services, ...",Yes,Yes,Yes,Yes,Yes,Yes,Yes,WI

In [24]:
# Display how many clinics are in the dataset
total_clinics = df3['OrderID'].nunique()
print(f"Total number of clinics in the dataset: {total_clinics}")

Total number of clinics in the dataset: 443

In [25]:
# chceck the data type of total_clinics
type(total_clinics)
# it's an integer, change it to float
total_clinics = float(total_clinics)

In [26]:
# filter df3 to only rows where either "DonorEgg" == Yes or "DonorEmbryo"== Yes
df3 = df3[(df3['DonorEgg'] == 'Yes') | (df3['DonorEmbryo'] == 'Yes')]

In [27]:
df3

,OrderID,PrevClinName1,PrevClinName2,ClinCityCode,ClinStateCode,IVF_Rate,GIFT_Rate,ZIFT_Rate,Combo_Rate,ICSI_Rate,...,ThwDnrEmbryosRate,CurrClinNameAll,DonorEgg,DonorEmbryo,SingleWomen,Surrogates,Cryopreservation,SART_Member,Accreditation,state_code
0,1,ALABAMA FERTILITY SPECIALISTS,NaN,BIRMINGHAM,ALABAMA,100%,0%,0%,0%,38%,...,1.5,Alabama Fertility Specialists,Yes,Yes,Yes,No,Yes,Yes,Yes,AL
1,2,ART FERTILITY PROGRAM OF ALABAMA,NaN,BIRMINGHAM,ALABAMA,100%,0%,0%,0%,88%,...,2.0,ART Fertility Program of Alabama,Yes,Yes,Yes,Yes,Yes,Yes,Yes,AL
2,3,UNIVERSITY OF ALABAMA AT BIRMINGHAM,NaN,BIRMINGHAM,ALABAMA,100%,0%,0%,0%,58%,...,2.0,University of Alabama at Birmingham,Yes,No,Yes,Yes,Yes,Yes,Yes,AL
3,4,"HUNTSVILLE REPRODUCTIVE MEDICINE, PC",NaN,HUNTSVILLE,ALABAMA,100%,0%,0%,0%,76%,...,2.1,"Huntsville Reproductive Medicine, PC",Yes,Yes,Yes,Yes,Yes,No,No,AL
4,5,CENTER FOR REPRODUCTIVE MEDICINE,NaN,MOBILE,ALABAMA,100%,0%,0%,0%,84%,...,NaN,Center for Reproductive Medicine,Yes,Yes,No,Yes,Yes,Yes,Yes,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
437,438,UNIVERSITY OF WISCONSIN-GENERATIONS FERTILITY ...,NaN,MIDDLETON,WISCONSIN,100%,0%,0%,0%,43%,...,2.0,University of Wisconsin-Generations Fertility ...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,WI
438,439,WISCONSIN FERTILITY INSTITUTE,NaN,MIDDLETON,WISCONSIN,100%,0%,0%,0%,94%,...,2.2,Wisconsin Fertility Institute,Yes,Yes,Yes,Yes,Yes,Yes,Yes,WI
439,440,REPRODUCTIVE MEDICINE CENTER,FROEDTERT-MEDICAL COLLEGE,MILWAUKEE,WISCONSIN,100%,0%,0%,0%,92%,...,1.8,"Reproductive Medicine Center, Froedtert-Medica...",Yes,Yes,Yes,Yes,Yes,Yes,Yes,WI
440,441,REPRODUCTIVE SPECIALTY CENTER,NaN,MILWAUKEE,WISCONSIN,100%,0%,0%,0%,46%,...,NaN,Reproductive Specialty Center,Yes,No,Yes,Yes,Yes,Yes,Yes,WI
442,443,"AURORA HEALTH CARE-AURORA FERTILITY SERVICES, ...",NaN,WEST ALLIS,WISCONSIN,100%,0%,0%,0%,92%,...,2.0,"Aurora Health Care-Aurora Fertility Services, ...",Yes,Yes,Yes,Yes,Yes,Yes,Yes,WI

In [28]:
# count the unique clinics where patients used donor eggs or embryos
donor_services_clinics = df3[(df3['DonorEgg'] == 'Yes') | (df3['DonorEmbryo'] == 'Yes')].nunique()
print(f"Clinics offering donor eggs or embryos services in 2010: {donor_services_clinics['OrderID']}")

Clinics offering donor eggs or embryos services in 2010: 406

In [29]:
donor_services_clinics = donor_services_clinics['OrderID']

In [30]:
# calculate the percentage of clinics in which patients used donor eggs or embryos in 2010

percentage_of_donor_clinics = (donor_services_clinics / total_clinics) * 100
percentage_of_donor_clinics = percentage_of_donor_clinics.round(2)

print (f"Percentage of clinics in which patients used donor eggs or embryos in 2010: {percentage_of_donor_clinics}%")

Percentage of clinics in which patients used donor eggs or embryos in 2010: 91.65%

## Dataset 4: 2020 CDC Data

In [5]:
# read csv "Preliminary-2020-National-Summary-Clinic-Table.xlsx" in the "Input" folder
df4 = pd.read_excel('./Input/Preliminary-2020-National-Summary-Clinic-Table.xlsx', sheet_name='Clinic Table Data Records')
df4

,OrderID,CurrentClinicName1,CurrentClinicName2,CurrentClinicCity,CurrentClinicState,MedicalDirector,ND_NumIntentRet1,ND_NumIntentRet2,ND_NumIntentRet3,ND_NumIntentRet4,...,ReasonUnexplained,DonorEggService,DonatedEmbryoService,EmbryoCryoService,EggCryoService,GestCarrierService,SARTmember,LabAccred,NumResearch,CurrentStateAbbrev
0,1,ALABAMA FERTILITY SPECIALISTS,NaN,BIRMINGHAM,ALABAMA,"Mamie R. McLean, MD",102,48,36,31,...,9%,Yes,Yes,Yes,Yes,Yes,Yes,Yes,0,AL
1,2,UNIVERSITY OF ALABAMA AT BIRMINGHAM,REPRODUCTIVE ENDOCRINOLOGY AND INFERTILITY,BIRMINGHAM,ALABAMA,"Deidre D Gunn, MD",21,10,9,7,...,9%,Yes,Yes,Yes,Yes,Yes,Yes,Yes,0,AL
2,3,FERTILITY INSTITUTE OF NORTH ALABAMA,NaN,HUNTSVILLE,ALABAMA,"Brett Davenport, MD",17,5,*,*,...,5%,Yes,No,Yes,Yes,Yes,No,Yes,0,AL
3,4,CENTER FOR REPRODUCTIVE MEDICINE,NaN,MOBILE,ALABAMA,"George T. Koulianos, MD",54,61,20,18,...,3%,Yes,Yes,Yes,Yes,Yes,Yes,Yes,0,AL
4,5,"KATIE OSTROM MD, LLC",NaN,HOMER,ALASKA,"Gary Levy, MD",0,0,0,0,...,* / 16,Yes,No,Yes,Yes,Yes,No,No,0,AK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
444,445,FROEDTERT & MEDICAL COLLEGE OF WISCONSIN,REPRODUCTIVE MEDICINE CENTER,MENOMONEE FALLS,WISCONSIN,"Katherine Schoyer, MD",146,51,41,20,...,11%,Yes,Yes,Yes,Yes,Yes,Yes,Yes,0,WI
445,446,UNIVERSITY OF WISCONSIN-GENERATIONS FERTILITY ...,NaN,MIDDLETON,WISCONSIN,"Bala Bhagavath, MD",106,33,28,*,...,18%,Yes,No,Yes,Yes,Yes,Yes,Yes,0,WI
446,447,WISCONSIN FERTILITY INSTITUTE,NaN,MIDDLETON,WISCONSIN,"Elizabeth Pritts, MD",66,44,22,18,...,13%,Yes,Yes,Yes,Yes,Yes,Yes,Yes,0,WI
447,448,REPRODUCTIVE SPECIALTY CENTER,NaN,MILWAUKEE,WISCONSIN,"Grace M. Janik, MD",8,7,6,*,...,0%,Yes,Yes,Yes,Yes,Yes,Yes,Yes,0,WI
448,449,"AURORA HEALTH CARE-AURORA FERTILITY SERVICES, ...",NaN,WEST ALLIS,WISCONSIN,"Katherine A Green, MD",65,35,22,15,...,1%,Yes,Yes,Yes,Yes,Yes,Yes,Yes,0,WI

In [32]:
# count unique OrderID
total_clinics_2020 = df4['OrderID'].nunique()
print(f"Total number of clinics in 2020: {total_clinics_2020}")

Total number of clinics in 2020: 449

In [33]:
df4['TotNumCyclesAll']

0      518
1      149
2      179
3      328
4       16
      ...
444    540
445    317
446    589
447     41
448    404
Name: TotNumCyclesAll, Length: 449, dtype: object

In [34]:
# remove all commas in the "TotNumCyclesAll" column
df4['TotNumCyclesAll'] = df4['TotNumCyclesAll'].str.replace(',', '')

# change the data type of "TotNumCyclesAll" to float
df4['TotNumCyclesAll'] = df4['TotNumCyclesAll'].astype(float)

In [35]:
# sum all the cycles in 'TotNumCyclesAll'
total_cycles_2020 = df4['TotNumCyclesAll'].sum()
print(f"National total cycles in 2020: {total_cycles_2020}")

National total cycles in 2020: 326468.0

In [36]:
# filter to only rows where either "DonorEggService" == Yes or "DonatedEmbryoService"== Yes
df4 = df4[(df4['DonorEggService'] == 'Yes') | (df4['DonatedEmbryoService'] == 'Yes')]
df4

,OrderID,CurrentClinicName1,CurrentClinicName2,CurrentClinicCity,CurrentClinicState,MedicalDirector,ND_NumIntentRet1,ND_NumIntentRet2,ND_NumIntentRet3,ND_NumIntentRet4,...,ReasonUnexplained,DonorEggService,DonatedEmbryoService,EmbryoCryoService,EggCryoService,GestCarrierService,SARTmember,LabAccred,NumResearch,CurrentStateAbbrev
0,1,ALABAMA FERTILITY SPECIALISTS,NaN,BIRMINGHAM,ALABAMA,"Mamie R. McLean, MD",102,48,36,31,...,9%,Yes,Yes,Yes,Yes,Yes,Yes,Yes,0,AL
1,2,UNIVERSITY OF ALABAMA AT BIRMINGHAM,REPRODUCTIVE ENDOCRINOLOGY AND INFERTILITY,BIRMINGHAM,ALABAMA,"Deidre D Gunn, MD",21,10,9,7,...,9%,Yes,Yes,Yes,Yes,Yes,Yes,Yes,0,AL
2,3,FERTILITY INSTITUTE OF NORTH ALABAMA,NaN,HUNTSVILLE,ALABAMA,"Brett Davenport, MD",17,5,*,*,...,5%,Yes,No,Yes,Yes,Yes,No,Yes,0,AL
3,4,CENTER FOR REPRODUCTIVE MEDICINE,NaN,MOBILE,ALABAMA,"George T. Koulianos, MD",54,61,20,18,...,3%,Yes,Yes,Yes,Yes,Yes,Yes,Yes,0,AL
4,5,"KATIE OSTROM MD, LLC",NaN,HOMER,ALASKA,"Gary Levy, MD",0,0,0,0,...,* / 16,Yes,No,Yes,Yes,Yes,No,No,0,AK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
444,445,FROEDTERT & MEDICAL COLLEGE OF WISCONSIN,REPRODUCTIVE MEDICINE CENTER,MENOMONEE FALLS,WISCONSIN,"Katherine Schoyer, MD",146,51,41,20,...,11%,Yes,Yes,Yes,Yes,Yes,Yes,Yes,0,WI
445,446,UNIVERSITY OF WISCONSIN-GENERATIONS FERTILITY ...,NaN,MIDDLETON,WISCONSIN,"Bala Bhagavath, MD",106,33,28,*,...,18%,Yes,No,Yes,Yes,Yes,Yes,Yes,0,WI
446,447,WISCONSIN FERTILITY INSTITUTE,NaN,MIDDLETON,WISCONSIN,"Elizabeth Pritts, MD",66,44,22,18,...,13%,Yes,Yes,Yes,Yes,Yes,Yes,Yes,0,WI
447,448,REPRODUCTIVE SPECIALTY CENTER,NaN,MILWAUKEE,WISCONSIN,"Grace M. Janik, MD",8,7,6,*,...,0%,Yes,Yes,Yes,Yes,Yes,Yes,Yes,0,WI
448,449,"AURORA HEALTH CARE-AURORA FERTILITY SERVICES, ...",NaN,WEST ALLIS,WISCONSIN,"Katherine A Green, MD",65,35,22,15,...,1%,Yes,Yes,Yes,Yes,Yes,Yes,Yes,0,WI

In [37]:
# count the unique clinics where patients used donor eggs or embryos in 2020
donor_services_clinics_2020 = df4[(df4['DonorEggService'] == 'Yes') | (df4['DonatedEmbryoService'] == 'Yes')].nunique()
print(f"Clinics offering donor eggs or embryos services in 2020: {donor_services_clinics_2020['OrderID']}")

Clinics offering donor eggs or embryos services in 2020: 406

In [38]:
#display every row only with columns  Donor_NumTrans1, Donor_NumTrans2, Donor_NumTrans3, Donor_NumTrans4 
df4_donor = df4[['Donor_NumTrans1', 'Donor_NumTrans2', 'Donor_NumTrans3', 'Donor_NumTrans4']]

In [39]:
# check the dtype of the columns
df4_donor.dtypes

Donor_NumTrans1    object
Donor_NumTrans2    object
Donor_NumTrans3    object
Donor_NumTrans4    object
dtype: object

In [46]:
# change 'Donor_NumTrans1', 'Donor_NumTrans2', 'Donor_NumTrans3', 'Donor_NumTrans4' to float, before that replace all "*" with nan
df4_donor = df4_donor.replace('*', np.nan)
df4_donor = df4_donor.astype(float)
df4_donor.dtypes

Donor_NumTrans1    float64
Donor_NumTrans2    float64
Donor_NumTrans3    float64
Donor_NumTrans4    float64
dtype: object

In [50]:
# Sum Donor_NumTrans1, Donor_NumTrans2, Donor_NumTrans3, Donor_NumTrans4 of each row, and put the number in a new column "TotalDonorTransfers"
df4.loc[:, 'TotalDonorTransfers'] = df4['Donor_NumTrans1']+ df4['Donor_NumTrans2'] + df4['Donor_NumTrans3'] + df4['Donor_NumTrans4']
df4.loc[:, 'TotalDonorTransfers'] = df4['TotalDonorTransfers']

In [ ]:
print(f"Total number of donor transfers in 2020: {df4['TotalDonorTransfers'].sum()}")

Total number of donor transfers in 2020: 19872.0

In [ ]:
# calculate the percentage of cycles in which patients used donor eggs or embryos in 2020
pecentage_of_donor_cycles_2020 = (df4['TotalDonorTransfers'].sum() / total_cycles_2020) * 100
print(f"Percentage of cycles that were donor eggs or embryos transfers in 2020: {pecentage_of_donor_cycles_2020:.2f}% (probably not referencable)")

Percentage of cycles that were donor eggs or embryos transfers in 2020: 6.09% (probably not referencable)

## Join 2010 and 2020 data

In [6]:
df3_select_columns = df3[['PrevClinName1', 'PrevClinName2',	'ClinCityCode',	'ClinStateCode', 'MedicalDirector']]
df4_select_columns = df4[['CurrentClinicName1', 'CurrentClinicName2', 'CurrentClinicCity', 'CurrentClinicState' ,'MedicalDirector']]
merged_on_md = df3_select_columns.merge(df4_select_columns, on='MedicalDirector', how='inner')
merged_on_md

,PrevClinName1,PrevClinName2,ClinCityCode,ClinStateCode,MedicalDirector,CurrentClinicName1,CurrentClinicName2,CurrentClinicCity,CurrentClinicState
0,UNIVERSITY OF ALABAMA AT BIRMINGHAM,NaN,BIRMINGHAM,ALABAMA,"Gordon W. Bates, MD",SCOTT & WHITE CLINIC-TEMPLE,NaN,TEMPLE,TEXAS
1,CENTER FOR REPRODUCTIVE MEDICINE,NaN,MOBILE,ALABAMA,"George T. Koulianos, MD",CENTER FOR REPRODUCTIVE MEDICINE,NaN,MOBILE,ALABAMA
2,SOUTHWEST FERTILITY CENTER,NaN,PHOENIX,ARIZONA,"Sujatha Gunnala, MD",SOUTHWEST FERTILITY CENTER,NaN,PHOENIX,ARIZONA
3,ARIZONA ASSOCIATES FOR REPRODUCTIVE HEALTH,NaN,SCOTTSDALE,ARIZONA,"Ketan S. Patel, MD",ARIZONA ASSOCIATES FOR REPRODUCTIVE HEALTH,ACFS FERTILITY,SCOTTSDALE,ARIZONA
4,IVF PHOENIX,NaN,SCOTTSDALE,ARIZONA,"John L. Couvaras, MD",IVF PHOENIX,NaN,SCOTTSDALE,ARIZONA
...,...,...,...,...,...,...,...,...,...
207,NORTHWEST CENTER FOR REPRODUCTIVE SCIENCES,NaN,KIRKLAND,WASHINGTON,"Michael S. Opsahl, MD",POMA FERTILITY,NaN,KIRKLAND,WASHINGTON
208,OLYMPIA WOMEN'S HEALTH,NaN,OLYMPIA,WASHINGTON,"James F. Moruzzi, MD, PhD",OLYMPIA WOMEN'S HEALTH,NaN,OLYMPIA,WASHINGTON
209,PACIFIC NORTHWEST FERTILITY AND IVF SPECIALISTS,NaN,SEATTLE,WASHINGTON,"Lorna A. Marshall, MD",PACIFIC NORTHWEST FERTILITY AND IVF SPECIALISTS,NaN,SEATTLE,WASHINGTON
210,CENTER FOR ADVANCED REPRODUCTIVE MEDICINE,NaN,HUNTINGTON,WEST VIRGINIA,"William N. Burns, MD",CABELL HUNTINGTON HOSPITAL,CENTER FOR ADVANCED REPRODUCTIVE MEDICINE,HUNTINGTON,WEST VIRGINIA
211,REPRODUCTIVE SPECIALTY CENTER,NaN,MILWAUKEE,WISCONSIN,"Grace M. Janik, MD",REPRODUCTIVE SPECIALTY CENTER,NaN,MILWAUKEE,WISCONSIN

In [7]:
# import fuzzywuzzy
from fuzzywuzzy import fuzz

# get fuzzy match score for PrevClinName1 and CurrentClinicName1
merged_on_md['match_score'] = merged_on_md.apply(lambda x: fuzz.ratio(x['PrevClinName1'], x['CurrentClinicName1']), axis=1)
merged_on_md

/Users/charlenelin/.pyenv/versions/3.11.6/lib/python3.11/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

,PrevClinName1,PrevClinName2,ClinCityCode,ClinStateCode,MedicalDirector,CurrentClinicName1,CurrentClinicName2,CurrentClinicCity,CurrentClinicState,match_score
0,UNIVERSITY OF ALABAMA AT BIRMINGHAM,NaN,BIRMINGHAM,ALABAMA,"Gordon W. Bates, MD",SCOTT & WHITE CLINIC-TEMPLE,NaN,TEMPLE,TEXAS,13
1,CENTER FOR REPRODUCTIVE MEDICINE,NaN,MOBILE,ALABAMA,"George T. Koulianos, MD",CENTER FOR REPRODUCTIVE MEDICINE,NaN,MOBILE,ALABAMA,100
2,SOUTHWEST FERTILITY CENTER,NaN,PHOENIX,ARIZONA,"Sujatha Gunnala, MD",SOUTHWEST FERTILITY CENTER,NaN,PHOENIX,ARIZONA,100
3,ARIZONA ASSOCIATES FOR REPRODUCTIVE HEALTH,NaN,SCOTTSDALE,ARIZONA,"Ketan S. Patel, MD",ARIZONA ASSOCIATES FOR REPRODUCTIVE HEALTH,ACFS FERTILITY,SCOTTSDALE,ARIZONA,100
4,IVF PHOENIX,NaN,SCOTTSDALE,ARIZONA,"John L. Couvaras, MD",IVF PHOENIX,NaN,SCOTTSDALE,ARIZONA,100
...,...,...,...,...,...,...,...,...,...,...
207,NORTHWEST CENTER FOR REPRODUCTIVE SCIENCES,NaN,KIRKLAND,WASHINGTON,"Michael S. Opsahl, MD",POMA FERTILITY,NaN,KIRKLAND,WASHINGTON,14
208,OLYMPIA WOMEN'S HEALTH,NaN,OLYMPIA,WASHINGTON,"James F. Moruzzi, MD, PhD",OLYMPIA WOMEN'S HEALTH,NaN,OLYMPIA,WASHINGTON,100
209,PACIFIC NORTHWEST FERTILITY AND IVF SPECIALISTS,NaN,SEATTLE,WASHINGTON,"Lorna A. Marshall, MD",PACIFIC NORTHWEST FERTILITY AND IVF SPECIALISTS,NaN,SEATTLE,WASHINGTON,100
210,CENTER FOR ADVANCED REPRODUCTIVE MEDICINE,NaN,HUNTINGTON,WEST VIRGINIA,"William N. Burns, MD",CABELL HUNTINGTON HOSPITAL,CENTER FOR ADVANCED REPRODUCTIVE MEDICINE,HUNTINGTON,WEST VIRGINIA,18
211,REPRODUCTIVE SPECIALTY CENTER,NaN,MILWAUKEE,WISCONSIN,"Grace M. Janik, MD",REPRODUCTIVE SPECIALTY CENTER,NaN,MILWAUKEE,WISCONSIN,100

In [8]:
merged_on_md.to_csv('merged_on_md.csv', index=False)

In [16]:
merged_on_md.value_counts('MedicalDirector')

MedicalDirector
Lisa Farah-Eways, MD       2
William L. Gentry, MD      2
Kevin J. Doody, MD         2
Russell A. Foulk, MD       2
Carole L. Kowalczyk, MD    2
                          ..
James P. Lin, MD           1
James W. Akin, MD          1
Jane E. Miller, MD         1
Janelle O. Dorsett, MD     1
Zev Rosenwaks, MD          1
Name: count, Length: 207, dtype: int64

# Company Search Data

In [9]:
companies_df = pd.read_csv('Input/fertility-clinic-agency-list.csv')
companies_df = companies_df.sort_values(by='Agent')
companies_df

,Entity Information,Initial Filing Date,Status,Entity Type,Formed In,Agent
134,MARK SURROGACY INVESTMENT LLC (202113411118),05/11/2021,Active,Limited Liability Company - CA,CALIFORNIA,"AAA AMERICAN CPA, INC"
417,"FERTILITY LABORATORY CONSULTANTS, INC. (4696143)",02/05/2021,Active,Stock Corporation - Out of State - Stock,MASSACHUSETTS,AFTAB AHMED
443,FERTILITY UNITED LLC (201906310525),02/27/2019,Terminated,Limited Liability Company - CA,CALIFORNIA,ALLYSE ALEX
21,BABY JOY SURROGACY LLC (201900310319),12/24/2018,Terminated,Limited Liability Company - CA,CALIFORNIA,ALVIN CHEN
128,LOTUS INTERNATIOANL SURROGACY LLC (201822010607),08/06/2018,Suspended - FTB,Limited Liability Company - CA,CALIFORNIA,AMANDA ELIZABETH TROIANO
...,...,...,...,...,...,...
558,PACIFIC FERTILITY INSTITUTES U.S. HOLDING COMP...,06/18/2014,Suspended - FTB/SOS,Limited Liability Company - CA,CALIFORNIA,NaN
574,"RODEO FERTILITY PARTNERS, L.L.C. (201130010003)",10/26/2011,Terminated,Limited Liability Company - CA,CALIFORNIA,NaN
618,THE SOUTHERN CALIFORNIA FERTILITY INSTITUTE (6...,10/12/1971,Suspended - FTB,Nonprofit Corporation - CA - General,CALIFORNIA,NaN
619,"THRIVE FERTILITY CONSULTING, LLC (201712410041)",04/26/2017,Terminated,Limited Liability Company - CA,CALIFORNIA,NaN
624,US FERTILITY HOPE LLC (201536210066),12/18/2015,Suspended - FTB/SOS,Limited Liability Company - CA,CALIFORNIA,NaN

In [5]:
# show nan agents
companies_df[companies_df['Agent'].isna()]

,Entity Information,Initial Filing Date,Status,Entity Type,Formed In,Agent
30,BSC-EGG DONATION AND SURROGACY AGENCY INC. (38...,01/25/2016,Terminated,Stock Corporation - CA - General,CALIFORNIA,NaN
208,SURROGACY MANAGEMENT LLC (201408710217),03/25/2014,Terminated,Limited Liability Company - CA,CALIFORNIA,NaN
219,TRUSTED SURROGACY LLC (201828210076),10/04/2018,Active,Limited Liability Company - CA,CALIFORNIA,NaN
239,"EGG DONOR CONNECT, LLC (200722110272)",07/10/2007,Suspended - FTB,Limited Liability Company - CA,CALIFORNIA,NaN
242,"EGG DONORS OF LA JOLLA, INC. (4031081)",05/30/2017,Terminated,Stock Corporation - CA - General,CALIFORNIA,NaN
243,ELEVATE EGG DONOR AGENCY LLC (201813610416),05/07/2018,Terminated,Limited Liability Company - CA,CALIFORNIA,NaN
325,"CERES FERTILITY, A CALIFORNIA CORPORATION (228...",06/11/2001,Suspended - FTB,Stock Corporation - CA - General,CALIFORNIA,NaN
342,"EDEN FERTILITY CENTER OF NEWPORT BEACH, PC (42...",04/26/2019,Terminated,Stock Corporation - CA - Professional,CALIFORNIA,NaN
374,FERTILITY CENTER OF LOS ANGELES (528967),06/29/1967,Terminated,Nonprofit Corporation - CA - General,CALIFORNIA,NaN
376,"FERTILITY CENTER PARTNERS, L.P. (199227400007)",09/28/1992,Terminated,Limited Partnership - CA,CALIFORNIA,NaN
382,FERTILITY CONTROL (562935),02/14/1969,Suspended - FTB,Stock Corporation - CA - General,CALIFORNIA,NaN
399,"FERTILITY FUTURES INTERNATIONAL, LLC (20022601...",09/11/2002,Merged Out,Limited Liability Company - CA,CALIFORNIA,NaN
411,"FERTILITY INSTITUTE, INC. (252680)",03/26/1951,Suspended - FTB,Nonprofit Corporation - CA - General,CALIFORNIA,NaN
412,"FERTILITY INSTITUTE, INC. (895296)",08/21/1978,Suspended - FTB,Nonprofit Corporation - CA - Public Benefit,CALIFORNIA,NaN
558,PACIFIC FERTILITY INSTITUTES U.S. HOLDING COMP...,06/18/2014,Suspended - FTB/SOS,Limited Liability Company - CA,CALIFORNIA,NaN
574,"RODEO FERTILITY PARTNERS, L.L.C. (201130010003)",10/26/2011,Terminated,Limited Liability Company - CA,CALIFORNIA,NaN
618,THE SOUTHERN CALIFORNIA FERTILITY INSTITUTE (6...,10/12/1971,Suspended - FTB,Nonprofit Corporation - CA - General,CALIFORNIA,NaN
619,"THRIVE FERTILITY CONSULTING, LLC (201712410041)",04/26/2017,Terminated,Limited Liability Company - CA,CALIFORNIA,NaN
624,US FERTILITY HOPE LLC (201536210066),12/18/2015,Suspended - FTB/SOS,Limited Liability Company - CA,CALIFORNIA,NaN

In [10]:
# remove nan
companies_df = companies_df.dropna(subset=['Agent'])
companies_df

,Entity Information,Initial Filing Date,Status,Entity Type,Formed In,Agent
134,MARK SURROGACY INVESTMENT LLC (202113411118),05/11/2021,Active,Limited Liability Company - CA,CALIFORNIA,"AAA AMERICAN CPA, INC"
417,"FERTILITY LABORATORY CONSULTANTS, INC. (4696143)",02/05/2021,Active,Stock Corporation - Out of State - Stock,MASSACHUSETTS,AFTAB AHMED
443,FERTILITY UNITED LLC (201906310525),02/27/2019,Terminated,Limited Liability Company - CA,CALIFORNIA,ALLYSE ALEX
21,BABY JOY SURROGACY LLC (201900310319),12/24/2018,Terminated,Limited Liability Company - CA,CALIFORNIA,ALVIN CHEN
128,LOTUS INTERNATIOANL SURROGACY LLC (201822010607),08/06/2018,Suspended - FTB,Limited Liability Company - CA,CALIFORNIA,AMANDA ELIZABETH TROIANO
...,...,...,...,...,...,...
490,INCINTA FERTILITY INVESTMENT. LLC (201811610323),04/13/2018,Active,Limited Liability Company - Out of State,DELAWARE,dongsheng zhou
491,INCINTA FERTILITY MANAGEMENT.LLC (201814210399),05/11/2018,Active,Limited Liability Company - Out of State,DELAWARE,dongsheng zhou
500,INTERNATIONAL FERTILITY SERVICE INC. (3281683),03/01/2010,Active,Stock Corporation - CA - General,CALIFORNIA,dongsheng zhou
487,INCINTA FERTILITY CENTER L.L.C. (201619410088),07/05/2016,Active,Limited Liability Company - CA,CALIFORNIA,dongsheng zhou
321,Center for Endometriosis and Fertility (5805591),07/03/2023,Active,Stock Corporation - CA - Professional,CALIFORNIA,sadikah F Behbehani

In [7]:
# keep duplicate agents only
companies_df_duplicate_agents = companies_df[companies_df.duplicated(subset=['Agent'], keep=False)]
companies_df_duplicate_agents.to_csv('companies_df_duplicate_agents.csv', index=False)
companies_df_duplicate_agents

,Entity Information,Initial Filing Date,Status,Entity Type,Formed In,Agent
179,"SOCAL SURROGACY, INC. (3943500)",09/07/2016,Active,Stock Corporation - CA - General,CALIFORNIA,ANDREW R. GALE
180,"SOCAL SURROGACY, LLC (201812810238)",04/26/2018,Active,Limited Liability Company - CA,CALIFORNIA,ANDREW R. GALE
139,NAPPY ENDINGS SURROGACY AGENCY LLC (202035410071),12/16/2020,Active,Limited Liability Company - CA,CALIFORNIA,ANDREW VORZIMER
633,VORZIMER/MASSERMAN - FERTILITY AND FAMILY LAW ...,05/11/1994,Active,Stock Corporation - CA - General,CALIFORNIA,ANDREW VORZIMER
609,THE FERTILITY AND REPRODUCTIVE RIGHTS LEAGUE (...,07/07/2004,Suspended - FTB,Nonprofit Corporation - CA - Public Benefit,CALIFORNIA,ANGELA POOL HEGAMIN
...,...,...,...,...,...,...
162,PINEAPPLE SURROGACY LLC (202023010600),08/13/2020,Active,Limited Liability Company - CA,CALIFORNIA,ZENBUSINESS INC.
490,INCINTA FERTILITY INVESTMENT. LLC (201811610323),04/13/2018,Active,Limited Liability Company - Out of State,DELAWARE,dongsheng zhou
491,INCINTA FERTILITY MANAGEMENT.LLC (201814210399),05/11/2018,Active,Limited Liability Company - Out of State,DELAWARE,dongsheng zhou
500,INTERNATIONAL FERTILITY SERVICE INC. (3281683),03/01/2010,Active,Stock Corporation - CA - General,CALIFORNIA,dongsheng zhou
487,INCINTA FERTILITY CENTER L.L.C. (201619410088),07/05/2016,Active,Limited Liability Company - CA,CALIFORNIA,dongsheng zhou

In [8]:
companies_df_duplicate_agents.value_counts('Agent')

Agent
C T CORPORATION SYSTEM                                                                                     28
NO AGENT                                                                                                   20
LEGALZOOM.COM, INC.                                                                                        17
CSC - LAWYERS INCORPORATING SERVICE                                                                         8
REGISTERED AGENTS INC                                                                                       8
ZENBUSINESS INC.                                                                                            5
dongsheng zhou                                                                                              4
REPUBLIC REGISTERED AGENT INC.                                                                              4
UNITED STATES CORPORATION AGENTS, INC.                                                                      4
REGISTERED AGENT SOLUTIONS, INC.                                                                            3
Gregory Wiles                                                                                               3
KENIA GERMAN                                                                                                3
SHAHLA MELAMED                                                                                              3
NORTHWEST REGISTERED AGENT, INC.                                                                            3
CORPORATION SERVICE COMPANY WHICH WILL DO BUSINESS IN CALIFORNIA AS CSC - LAWYERS INCORPORATING SERVICE     3
SHUOFENG ZHAO                                                                                               3
JOSEPH SINGLETON                                                                                            3
CALIFORNIA REGISTERED AGENT INC                                                                             3
CALIFORNIA CORPORATE AGENTS, INC.                                                                           3
NEAL MARKOWITZ                                                                                              3
JAMES P LIN                                                                                                 3
PETER DENG                                                                                                  2
MINGMING WANG                                                                                               2
ROBERT TYLER                                                                                                2
PING WANG                                                                                                   2
RICHARD A GEISLER                                                                                           2
MICHAEL A DOWELL                                                                                            2
THOMAS LEE                                                                                                  2
TRUDI ATHERTON                                                                                              2
XIAOYAN ZHENG                                                                                               2
YANQING HAN                                                                                                 2
YULUN JIANG                                                                                                 2
MICHAEL VERMESH                                                                                             2
ANDREW R. GALE                                                                                              2
MAN MAN KWOK                                                                                                2
Dylan C Keezell                                                                                             2
ANGELA POOL HEGAMIN                                                                                         2
ANNA MARIAH SWAN                                                                                            2
ARLENE MORALES                                                                                              2
ASHIM KUMAR                                                                                                 2
CAMRAN NEZHAT                                                                                               2
CATHERINE WELCH                                                                                             2
CHRISTINE CHAVEZ                                                                                            2
CORLANDOS SCOTT                                                                                             2
DANIELLE LANE                                                                                               2
FEI WANG                                                                                                    2
LIN CHEN                                                                                                    2
FRED ROSENMUND                                                                                              2
GABRIEL BOGNER                                                                                              2
Haoming Chen                                                                                                2
JIANMIN SHEN                                                                                                2
KAI SONG                                                                                                    2
KRISTINE TYLER                                                                                              2
ANDREW VORZIMER                                                                                             2
LEGALCORP SOLUTIONS, INC                                                                                    2
LEGALINC REGISTERED AGENTS, INC.                                                                            2
KYLE FRANCIS                                                                                                2
Name: count, dtype: int64